### ISSUE TITLE
Hackage

### ISSUE THREAD

**Issue by sdiehl** [llvm-hs/llvm-hs-quote#11]
This port actually went a lot smoother than I thought. I'll keep polishing it and see if we get any more issues but I'll plan on first public release on Hackage end of February. I'll be giving a bunch of talks in Europe so would be nice to have all the software publically downloadable.

**Comment by cocreature** [comment]
Sorry for the lack of response on my part! I’ve somehow managed to miss this issue. Feel free to make a release when you think it’s ready. I’m generally in favor of release early, release often so I don’t think there is anything stopping a release.

**Comment by sdiehl** [comment]
indeed, I just closed the issue because I realized it was far past February. :wink:

**Comment by moll** [comment]
Any continued plans for putting it up on Hackage these days? Cheers
