### ISSUE TITLE
Loop Sugar

### ISSUE THREAD

**Issue by sdiehl** [llvm-hs/llvm-hs-quote#4]
It appears that in the original repository, the loop syntactic sugar was a planned feature but never implemented. I suppose we have the option to either go ahead and implement it or just omit that in the port. My feeling is that the purpose of higher level Haskell functions provider the IRBuilder kind of make adding this non-LLVM syntax to quasiquoter kind of less important and we should just stick to a vanilla LLVM parser.

https://github.com/llvm-hs/llvm-hs-quote/blob/master/test/LLVM/Quote/Test/Loops.hs#L29

**Comment by cocreature** [comment]
Afaict it actually has been implemented (e.g. https://github.com/llvm-hs/llvm-hs-quote/blob/master/src/LLVM/Quote/Parser/Parser.y#L758 and https://github.com/llvm-hs/llvm-hs-quote/blob/master/src/LLVM/Quote/Base.hs#L539) but in a slightly different form than the test suggest (in particular the `with` clauses don’t exist). That said I completely agree that they don’t provide a lot of value and removing them is the best course of action. In fact, we could consider (and I tend to be in favor of that) to also remove the SSA transformation and thereby stick even closer to vanilla LLVM IR. If someone wants to avoid having to SSA transform their IR then stack-allocation using `alloca` + `mem2reg` seems like a better option.

**Comment by sdiehl** [comment]
It appears that the `with i32 0 as %n` syntax was omitted or an extension from the implementation in `Parser.y`.

**Comment by tvh** [comment]
As I recall I only added the SSA transformation to make the loop transformation possible, so I wouldn't see a reason to keep it if the loop transformation was to be dropped.

**Comment by sdiehl** [comment]
Ok cool, I'll keep that in mind going forward.
